# Generated by Django 2.2 on 2019-04-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_imported', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('share_name', models.CharField(max_length=64)),
                ('server_name', models.CharField(max_length=64, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('tree_root', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_for', to='django_smb.RemotePath')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
