# Generated by Django 2.1.3 on 2018-11-26 11:22

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RemotePath',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('level',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='children',
                     to='django_smb.RemotePath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteLocation',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('share_name', models.CharField(max_length=64)),
                ('server_name', models.CharField(max_length=64, unique=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('tree_root',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     to='django_smb.RemotePath')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
