# Generated by Django 2.1.3 on 2018-11-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'SMB Files',
            },
        ),
        migrations.CreateModel(
            name='RemoteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('share_name', models.CharField(max_length=64)),
                ('server_name', models.CharField(max_length=64)),
                ('last_sync', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='remotefile',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_set', to='django_smb.RemoteLocation'),
        ),
    ]
