# Generated by Django 2.1.3 on 2018-11-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelocation',
            name='tree_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='django_smb.RemotePath'),
        ),
    ]
