# Generated by Django 2.1.3 on 2018-11-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelocation',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='remotelocation',
            name='server_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
