# Generated by Django 2.1.3 on 2018-11-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smb', '0002_auto_20181126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelocation',
            name='tree_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_smb.RemotePath'),
        ),
    ]
