# Generated by Django 2.1.3 on 2018-11-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_smb', '0003_auto_20181126_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelocation',
            name='tree_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_for', to='django_smb.RemotePath'),
        ),
    ]
