# Generated by Django 2.1.3 on 2018-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smb', '0004_auto_20181126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepath',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
